services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skynet

  db_test:
    image: postgres:15
    container_name: db_test
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${TEST_DATABASE_NAME:-test_db}
    ports:
      - "5433:5432"  # порт 5432 контейнера проброшен на порт 5433 хоста, чтобы избежать конфликта с другим контейнером
#    volumes:
#      - postgres_data_test:/var/lib/postgresql/data
    networks:
      - skynet

  app:
    build: .
    restart: always
    container_name: playit-auth-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - skynet
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

networks:
  skynet:
    external: true


# Volumes нужны, чтобы значения сохранялись вне зависимости от удаления либо рестарта контейнера
volumes:
  postgres_data:
#  postgres_data_test: # В принципе можно не пользоваться volumes для тестов, потому что все таблицы тестовой БД
# очищаются после окончания тестов

