services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - skynet

  app:
    build: .
    restart: always
    container_name: playit-auth-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
#    networks:
#      - skynet
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

#networks:
#  skynet:
#    external: true

# Volumes нужны, чтобы значения сохранялись вне зависимости от удаления либо рестарта контейнера
volumes:
  postgres_data:

