name: deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SERVER_HOST }}
        SSH_USERNAME: ${{ secrets.DEPLOY_USER }}
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
          cd ~/plait/PlayIt-auth-backend
          git pull
          docker compose -f docker-compose.yml down || true
          docker compose -f docker-compose.yml up -d || true
        '
